import Foundation
import XCTest
@testable import SpotifyLite

final class SpotifydConfigurationTests: XCTestCase {
    func testGeneratedConfigurationUsesExplicitMacAudioBackendAndEscapesTOML() {
        let rendered = SpotifydConfigurationFile.render(
            deviceName: "Listener's \"Mac\"\\Studio\nDesk",
            cacheDirectory: URL(fileURLWithPath: "/tmp/cache \\\"folder"),
            maxCacheSizeBytes: 123_456
        )

        XCTAssertTrue(rendered.hasPrefix("# Generated by Spotify Lite"))
        XCTAssertTrue(rendered.contains("[global]"))
        XCTAssertTrue(rendered.contains(#"device_name = "Listener's \"Mac\"\\Studio\nDesk""#))
        XCTAssertTrue(rendered.contains(#"cache_path = "/tmp/cache \\\"folder""#))
        XCTAssertTrue(rendered.contains(#"backend = "portaudio""#))
        XCTAssertTrue(rendered.contains(#"volume_controller = "softvol""#))
        XCTAssertTrue(rendered.contains("no_audio_cache = true"))
        XCTAssertTrue(rendered.contains("max_cache_size = 123456"))
        XCTAssertFalse(rendered.contains("\ndevice = "))
        XCTAssertFalse(rendered.contains("~"))
    }

    func testAudioOutputReportsMonoDefaultInsteadOfFallingBackToSpeakers() {
        let devices = [
            SpotifydAudioOutputDevice(id: 1, name: "Headset", outputChannels: 1, isDefault: true, isBuiltIn: false),
            SpotifydAudioOutputDevice(id: 2, name: "Mac Speakers", outputChannels: 2, isDefault: false, isBuiltIn: true)
        ]

        XCTAssertEqual(SpotifydAudioOutput.statusDescription(from: devices), "Headset")
    }

    func testAudioOutputReportsStereoSystemDefault() {
        let devices = [
            SpotifydAudioOutputDevice(id: 1, name: "Headphones", outputChannels: 2, isDefault: true, isBuiltIn: false),
            SpotifydAudioOutputDevice(id: 2, name: "Mac Speakers", outputChannels: 2, isDefault: false, isBuiltIn: true)
        ]

        XCTAssertEqual(SpotifydAudioOutput.statusDescription(from: devices), "Headphones")
    }

    func testRedactionRemovesOAuthAndBearerSecrets() {
        let raw = "https://callback/?code=secret-code&state=secret-state Authorization: Bearer abc.def_123"
        let redacted = SpotifydSupervisor.redact(raw)

        XCTAssertFalse(redacted.contains("secret-code"))
        XCTAssertFalse(redacted.contains("secret-state"))
        XCTAssertFalse(redacted.contains("abc.def_123"))
        XCTAssertTrue(redacted.contains("code=<redacted>"))
        XCTAssertTrue(redacted.contains("Bearer <redacted>"))
    }

    func testUnexpectedSessionShutdownIsRecognizedAsConnectionInterruption() {
        XCTAssertTrue(SpotifydSupervisor.isConnectionInterruption(
            "[stdout] [WARN] unexpected shutdown"
        ))
        XCTAssertTrue(SpotifydSupervisor.isConnectionInterruption(
            "[stdout] [ERROR] Connection to server closed."
        ))
        XCTAssertFalse(SpotifydSupervisor.isConnectionInterruption(
            "[stdout] [WARN] couldn't load context info"
        ))
    }

    func testSupervisorOnlyReturnsSupportedLocations() async {
        let root = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        let supervisor = SpotifydSupervisor(configuration: .init(applicationSupportDirectory: root))
        let installation = await supervisor.inspectInstallation()

        if let executable = installation.executableURL {
            XCTAssertTrue([
                "/opt/homebrew/bin/spotifyd",
                "/usr/local/bin/spotifyd"
            ].contains(executable.path))
        }
    }

    func testStartRequiresReceiverAuthenticationBeforeLaunching() async throws {
        let root = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: root) }

        let executable = root.appendingPathComponent("spotifyd")
        try Data("#!/bin/sh\necho spotifyd 0.4.2\n".utf8).write(to: executable)
        try FileManager.default.setAttributes([.posixPermissions: 0o700], ofItemAtPath: executable.path)

        let supervisor = SpotifydSupervisor(configuration: .init(
            userSelectedExecutableURL: executable,
            applicationSupportDirectory: root.appendingPathComponent("support")
        ))

        do {
            try await supervisor.start()
            XCTFail("Expected receiver authentication to be required")
        } catch let error as SpotifydSupervisorError {
            XCTAssertEqual(error, .authenticationRequired)
        }
    }

    func testDefaultAudioOutputChangeRestartsRunningReceiver() async throws {
        let root = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        let support = root.appendingPathComponent("support", isDirectory: true)
        let cache = support.appendingPathComponent("spotifyd-cache", isDirectory: true)
        try FileManager.default.createDirectory(at: cache, withIntermediateDirectories: true)
        try Data("{}".utf8).write(to: cache.appendingPathComponent("credentials.json"))
        defer { try? FileManager.default.removeItem(at: root) }

        let executable = root.appendingPathComponent("spotifyd")
        let script = """
        #!/bin/sh
        if [ "$1" = "--version" ]; then
          echo "spotifyd 0.4.2"
          exit 0
        fi
        echo "receiver-launched"
        trap 'exit 0' TERM INT
        while :; do sleep 1; done
        """
        try Data(script.utf8).write(to: executable)
        try FileManager.default.setAttributes([.posixPermissions: 0o700], ofItemAtPath: executable.path)

        let (changes, continuation) = AsyncStream<Void>.makeStream(bufferingPolicy: .bufferingNewest(1))
        let supervisor = SpotifydSupervisor(
            configuration: .init(
                userSelectedExecutableURL: executable,
                applicationSupportDirectory: support,
                gracefulStopDelay: .seconds(2)
            ),
            defaultAudioOutputChanges: { changes }
        )

        do {
            try await supervisor.start()
            let didLaunchInitially = await waitForLaunchCount(1, supervisor: supervisor)
            XCTAssertTrue(didLaunchInitially)

            continuation.yield(())

            let didRelaunch = await waitForLaunchCount(2, supervisor: supervisor)
            XCTAssertTrue(didRelaunch)
            let log = await supervisor.recentLogLines().joined(separator: "\n")
            XCTAssertTrue(log.contains("macOS default audio output changed"))
            await supervisor.stop()
            continuation.finish()
        } catch {
            continuation.finish()
            await supervisor.stop()
            throw error
        }
    }

    func testKeepAliveRefreshesReceiverAfterConnectSessionCloses() async throws {
        let root = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        let support = root.appendingPathComponent("support", isDirectory: true)
        let cache = support.appendingPathComponent("spotifyd-cache", isDirectory: true)
        try FileManager.default.createDirectory(at: cache, withIntermediateDirectories: true)
        try Data("{}".utf8).write(to: cache.appendingPathComponent("credentials.json"))
        defer { try? FileManager.default.removeItem(at: root) }

        let executable = root.appendingPathComponent("spotifyd")
        let script = """
        #!/bin/sh
        if [ "$1" = "--version" ]; then
          echo "spotifyd 0.4.2"
          exit 0
        fi
        echo "receiver-launched"
        if [ ! -f "connect-interrupted-once" ]; then
          touch "connect-interrupted-once"
          echo "Connection to server closed."
        fi
        trap 'exit 0' TERM INT
        while :; do sleep 1; done
        """
        try Data(script.utf8).write(to: executable)
        try FileManager.default.setAttributes([.posixPermissions: 0o700], ofItemAtPath: executable.path)

        let supervisor = SpotifydSupervisor(configuration: .init(
            userSelectedExecutableURL: executable,
            applicationSupportDirectory: support,
            gracefulStopDelay: .seconds(2),
            keepAliveRestartDelay: .milliseconds(20)
        ))

        do {
            try await supervisor.startKeepingAlive()
            let didRelaunch = await waitForLaunchCount(2, supervisor: supervisor)
            XCTAssertTrue(didRelaunch)
            let log = await supervisor.recentLogLines().joined(separator: "\n")
            XCTAssertTrue(log.contains("Refreshing stale Spotify Connect receiver session"))
            await supervisor.stopKeepingAlive()
        } catch {
            await supervisor.stopKeepingAlive()
            throw error
        }
    }

    private func waitForLaunchCount(_ count: Int, supervisor: SpotifydSupervisor) async -> Bool {
        for _ in 0..<100 {
            let lines = await supervisor.recentLogLines()
            if lines.filter({ $0.contains("receiver-launched") }).count >= count {
                return true
            }
            try? await Task.sleep(for: .milliseconds(50))
        }
        return false
    }
}
