import Foundation
import XCTest
@testable import SpotifyLite

final class SpotifydConfigurationTests: XCTestCase {
    func testGeneratedConfigurationUsesExplicitMacAudioBackendAndEscapesTOML() {
        let rendered = SpotifydConfigurationFile.render(
            deviceName: "Listener's \"Mac\"\\Studio\nDesk",
            cacheDirectory: URL(fileURLWithPath: "/tmp/cache \\\"folder"),
            maxCacheSizeBytes: 123_456,
            audioDeviceName: "MacBook Air Speakers"
        )

        XCTAssertTrue(rendered.hasPrefix("# Generated by Spotify Lite"))
        XCTAssertTrue(rendered.contains("[global]"))
        XCTAssertTrue(rendered.contains(#"device_name = "Listener's \"Mac\"\\Studio\nDesk""#))
        XCTAssertTrue(rendered.contains(#"cache_path = "/tmp/cache \\\"folder""#))
        XCTAssertTrue(rendered.contains(#"backend = "portaudio""#))
        XCTAssertTrue(rendered.contains(#"volume_controller = "softvol""#))
        XCTAssertTrue(rendered.contains("max_cache_size = 123456"))
        XCTAssertTrue(rendered.contains(#"device = "MacBook Air Speakers""#))
        XCTAssertFalse(rendered.contains("~"))
    }

    func testAudioOutputFallsBackFromMonoDefaultToBuiltInStereo() {
        let devices = [
            SpotifydAudioOutputDevice(id: 1, name: "Headset", outputChannels: 1, isDefault: true, isBuiltIn: false),
            SpotifydAudioOutputDevice(id: 2, name: "Mac Speakers", outputChannels: 2, isDefault: false, isBuiltIn: true)
        ]

        XCTAssertEqual(SpotifydAudioOutput.recommendedDeviceName(from: devices), "Mac Speakers")
    }

    func testAudioOutputKeepsStereoSystemDefault() {
        let devices = [
            SpotifydAudioOutputDevice(id: 1, name: "Headphones", outputChannels: 2, isDefault: true, isBuiltIn: false),
            SpotifydAudioOutputDevice(id: 2, name: "Mac Speakers", outputChannels: 2, isDefault: false, isBuiltIn: true)
        ]

        XCTAssertNil(SpotifydAudioOutput.recommendedDeviceName(from: devices))
    }

    func testRedactionRemovesOAuthAndBearerSecrets() {
        let raw = "https://callback/?code=secret-code&state=secret-state Authorization: Bearer abc.def_123"
        let redacted = SpotifydSupervisor.redact(raw)

        XCTAssertFalse(redacted.contains("secret-code"))
        XCTAssertFalse(redacted.contains("secret-state"))
        XCTAssertFalse(redacted.contains("abc.def_123"))
        XCTAssertTrue(redacted.contains("code=<redacted>"))
        XCTAssertTrue(redacted.contains("Bearer <redacted>"))
    }

    func testSupervisorOnlyReturnsSupportedLocations() async {
        let root = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        let supervisor = SpotifydSupervisor(configuration: .init(applicationSupportDirectory: root))
        let installation = await supervisor.inspectInstallation()

        if let executable = installation.executableURL {
            XCTAssertTrue([
                "/opt/homebrew/bin/spotifyd",
                "/usr/local/bin/spotifyd"
            ].contains(executable.path))
        }
    }

    func testStartRequiresReceiverAuthenticationBeforeLaunching() async throws {
        let root = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: root) }

        let executable = root.appendingPathComponent("spotifyd")
        try Data("#!/bin/sh\necho spotifyd 0.4.2\n".utf8).write(to: executable)
        try FileManager.default.setAttributes([.posixPermissions: 0o700], ofItemAtPath: executable.path)

        let supervisor = SpotifydSupervisor(configuration: .init(
            userSelectedExecutableURL: executable,
            applicationSupportDirectory: root.appendingPathComponent("support")
        ))

        do {
            try await supervisor.start()
            XCTFail("Expected receiver authentication to be required")
        } catch let error as SpotifydSupervisorError {
            XCTAssertEqual(error, .authenticationRequired)
        }
    }
}
