import Foundation

struct SpotifydSupervisorConfiguration: Sendable {
    var userSelectedExecutableURL: URL?
    var applicationSupportDirectory: URL
    var deviceName: String
    var maxCacheSizeBytes: Int
    var logTailLineLimit: Int
    var logFileMaxBytes: Int
    var gracefulStopDelay: Duration

    init(
        userSelectedExecutableURL: URL? = nil,
        applicationSupportDirectory: URL = Self.defaultApplicationSupportDirectory,
        deviceName: String = Self.defaultDeviceName,
        maxCacheSizeBytes: Int = 1_000_000_000,
        logTailLineLimit: Int = 300,
        logFileMaxBytes: Int = 512_000,
        gracefulStopDelay: Duration = .seconds(2)
    ) {
        self.userSelectedExecutableURL = userSelectedExecutableURL
        self.applicationSupportDirectory = applicationSupportDirectory
        self.deviceName = deviceName
        self.maxCacheSizeBytes = max(0, maxCacheSizeBytes)
        self.logTailLineLimit = max(1, logTailLineLimit)
        self.logFileMaxBytes = max(8_192, logFileMaxBytes)
        self.gracefulStopDelay = gracefulStopDelay
    }

    static var defaultApplicationSupportDirectory: URL {
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first
            ?? URL(fileURLWithPath: NSTemporaryDirectory(), isDirectory: true)
        return base.appendingPathComponent("SpotifyLite", isDirectory: true)
    }

    static var defaultDeviceName: String {
        let hostName = Host.current().localizedName?.trimmingCharacters(in: .whitespacesAndNewlines)
        return "Spotify Lite — \((hostName?.isEmpty == false ? hostName : nil) ?? "Mac")"
    }

    var cacheDirectory: URL {
        applicationSupportDirectory.appendingPathComponent("spotifyd-cache", isDirectory: true)
    }

    var configFile: URL {
        applicationSupportDirectory.appendingPathComponent("spotifyd.conf", isDirectory: false)
    }

    var logDirectory: URL {
        applicationSupportDirectory.appendingPathComponent("Logs", isDirectory: true)
    }
}

enum SpotifydConfigurationFile {
    static func render(
        deviceName: String,
        cacheDirectory: URL,
        maxCacheSizeBytes: Int
    ) -> String {
        """
        # Generated by Spotify Lite. spotifyd owns all credential files in cache_path.
        [global]
        device_name = \(tomlString(deviceName))
        device_type = "computer"
        cache_path = \(tomlString(cacheDirectory.path))
        no_audio_cache = false
        max_cache_size = \(max(0, maxCacheSizeBytes))
        backend = "portaudio"
        volume_controller = "softvol"
        bitrate = 320
        disable_discovery = false

        """
    }

    static func tomlString(_ value: String) -> String {
        var result = "\""
        for scalar in value.unicodeScalars {
            switch scalar.value {
            case 0x08: result += "\\b"
            case 0x09: result += "\\t"
            case 0x0A: result += "\\n"
            case 0x0C: result += "\\f"
            case 0x0D: result += "\\r"
            case 0x22: result += "\\\""
            case 0x5C: result += "\\\\"
            case 0x00...0x1F, 0x7F:
                result += String(format: "\\u%04X", scalar.value)
            default:
                result.unicodeScalars.append(scalar)
            }
        }
        result += "\""
        return result
    }
}
